<a href="https://colab.research.google.com/github/SilverIsle/demo-repo/blob/main/veriety.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch as pt
t=pt.tensor([[1,2]])

In [ ]:
x=pt.stack([t,t,t],dim=0)
print(x.shape)
print(x)

torch.Size([3, 1, 2])
tensor([[[1, 2]],

        [[1, 2]],

        [[1, 2]]])


In [ ]:
x=pt.stack([t,t,t],dim=1)
print(x.shape)
print(x)

torch.Size([1, 3, 2])
tensor([[[1, 2],
         [1, 2],
         [1, 2]]])


In [ ]:
x=pt.stack([t,t,t],dim=2)
print(x.shape)
print(x)

torch.Size([1, 2, 3])
tensor([[[1, 1, 1],
         [2, 2, 2]]])


In [ ]:
t=pt.tensor([[[1,2]],[[1,2]],[[1,2]]])
t

tensor([[[4, 2]],

        [[1, 2]],

        [[1, 2]]])

In [ ]:
t[:,:,0]

tensor([[4],
        [1],
        [1]])